import React from 'react';
import LegalDocument from '../components/common/LegalDocument';
import { SITE_CONFIG } from '../config/site';
import { useTranslation } from '../hooks/useTranslation';

const Privacy = () => {
  const { isEnglish } = useTranslation('common');
  const sections = isEnglish ? [
    { title: 'Controller and scope', content: [`Asya City ("we", "us" or "our") operates this website and may provide legal, employment, accident, vehicle, housing, property development, sale, purchase and site-management related services in Ankara and elsewhere in Türkiye. This policy explains how we process personal data when you browse the website, contact us, submit an application, request a quote or communicate with us.`] },
    { title: 'Data we may collect', content: ['We may collect your name, identity and contact details, email address, telephone number, address, site or property details, employment information, accident or vehicle-incident information, documents and messages that you choose to send to us.', 'Technical information may include IP address, browser type, device information, pages visited, referral data and security logs. We only request information that is reasonably relevant to the service or request.'] },
    { title: 'Why we use your data', content: ['We use data to answer enquiries, prepare legal or property-service proposals, manage appointments, review employment and salary matters, assess accident or vehicle-related requests, support housing and property transactions, manage sites, process applications, communicate updates, prevent fraud and protect the security of our systems.', 'Where required, processing is based on your consent, performance of a requested service or contract, compliance with a legal obligation, establishment or protection of a legal right, or our legitimate operational interests.'] },
    { title: 'Special-category and case information', content: ['Accident, health, employment, identity, financial and legal case information can be sensitive. Please do not send unnecessary medical records, identity documents or confidential evidence through an ordinary contact form. We may request secure document delivery after an initial review and will process such material only when necessary and permitted by applicable law.'] },
    { title: 'Legal documents and case submissions', content: ['If you send a petition, court document, accident report, vehicle record, insurance correspondence, photograph or other case material, we process it to understand your request, assess whether we can assist, prepare a response and maintain necessary professional records. Documents may contain information about other people, so you should only share material that you are authorised to provide.', 'Please redact unnecessary identity numbers, signatures, bank details, medical information and contact details before sending documents through a general form. Sending a document does not mean that it has been formally served, filed with a court or accepted as evidence.'] },
    { title: 'Sharing and service providers', content: ['We may share relevant information with authorised lawyers, consultants, property professionals, accountants, insurers, technical providers, hosting providers, communication services and public authorities where legally required or necessary to provide the requested service. We do not sell personal data.', 'Service providers may process data on our instructions. We require appropriate confidentiality and security measures and limit access to people who need the information.'] },
    { title: 'International transfers', content: ['Some hosting, email, analytics or form-delivery providers may process information outside Türkiye. Where this occurs, we will use the safeguards required by applicable Turkish data-protection rules and, where relevant, other applicable privacy laws.'] },
    { title: 'Retention and security', content: ['We keep personal data only for as long as reasonably necessary for the purpose collected, legal obligations, professional records, dispute resolution and limitation periods. We use access controls, reasonable technical measures and organisational safeguards, but no internet transmission can be guaranteed completely secure.'] },
    { title: 'Cookies and analytics', content: ['The website may use essential cookies and similar technologies for operation, language, theme, security and basic analytics. You can restrict cookies through your browser. Blocking essential cookies may affect some features. Any optional analytics or marketing tools should be enabled only in accordance with applicable consent requirements.'] },
    { title: 'Your rights and requests', content: [`Subject to applicable law, you may ask about access, correction, deletion, restriction, objection, portability or withdrawal of consent. Send requests to ${SITE_CONFIG.company.email} with enough information for us to identify the request. We may need to verify identity before responding. You may also contact the competent Turkish data-protection authority where applicable.`] },
    { title: 'Children and third-party links', content: ['The website is not directed to children. We do not knowingly collect children\'s data through the forms. Links to LinkedIn, messaging services, payment providers or other websites are governed by those providers\' own policies, not this policy.'] },
    { title: 'Changes and contact', content: [`We may update this policy when our services, technology or legal obligations change. The current version will be posted on this page. For privacy questions, contact ${SITE_CONFIG.company.email}.`] },
  ] : [
    { title: 'Veri sorumlusu ve kapsam', content: [`Asya City ("biz") bu web sitesini işletir; Ankara ve Türkiye'nin diğer bölgelerinde hukuk, iş ve ücret uyuşmazlıkları, kaza, araç, konut, gayrimenkul geliştirme, alım-satım ve site yönetimiyle ilgili hizmetler sunabilir. Bu politika; siteyi ziyaret ettiğinizde, iletişim kurduğunuzda, başvuru veya teklif formu gönderdiğinizde verilerin nasıl işlendiğini açıklar.`] },
    { title: 'İşlenebilecek veriler', content: ['Adınız, iletişim bilgileriniz, e-posta ve telefon numaranız, adresiniz, site veya gayrimenkul bilgileri, iş ve çalışma bilgileri, kaza veya araç olayı bilgileri, belgeler ve kendi iradenizle gönderdiğiniz mesajlar işlenebilir.', 'Site kullanımı sırasında IP adresi, tarayıcı ve cihaz bilgileri, ziyaret edilen sayfalar, yönlendirme bilgileri ve güvenlik kayıtları da işlenebilir. Hizmet veya talep için gerekli olmayan bilgileri istememeye çalışırız.'] },
    { title: 'Verilerin kullanım amaçları', content: ['Veriler; talepleri yanıtlamak, hukuki veya gayrimenkul hizmet teklifi hazırlamak, görüşme planlamak, iş ve ücret uyuşmazlıklarını, kaza veya araç taleplerini değerlendirmek, konut ve gayrimenkul işlemlerini desteklemek, site yönetmek, başvuruları değerlendirmek, güncelleme göndermek ve sistem güvenliğini sağlamak için kullanılır.', 'İşleme; açık rıza, talep edilen hizmetin veya sözleşmenin yürütülmesi, hukuki yükümlülük, bir hakkın kurulması veya korunması ya da meşru işletme menfaati gibi hukuki sebeplere dayanabilir.'] },
    { title: 'Özel nitelikli ve dosya bilgileri', content: ['Kaza, sağlık, çalışma, kimlik, mali ve hukuki dosya bilgileri hassas olabilir. Gereksiz sağlık raporu, kimlik belgesi veya delili genel iletişim formundan göndermeyin. Gerekirse ilk incelemeden sonra güvenli belge aktarımı talep edebilir ve bu bilgileri yalnızca gerekli ve hukuken izin verilen ölçüde işleriz.'] },
    { title: 'Hukuki belgeler ve dosya gönderimleri', content: ['Dilekçe, mahkeme belgesi, kaza tutanağı, araç kaydı, sigorta yazışması, fotoğraf veya başka bir dosya belgesi gönderirseniz; talebinizi anlamak, yardımcı olup olamayacağımızı değerlendirmek, yanıt hazırlamak ve gerekli mesleki kayıtları tutmak amacıyla işleriz. Başka kişilere ait bilgiler içeren belgeleri yalnızca paylaşma yetkiniz varsa gönderin.', 'Genel bir form üzerinden belge göndermeden önce gereksiz kimlik numarası, imza, banka bilgisi, sağlık bilgisi ve iletişim bilgilerini karartın. Belge göndermek, belgenin mahkemeye tebliğ edildiği, dosyaya sunulduğu veya delil olarak kabul edildiği anlamına gelmez.'] },
    { title: 'Aktarım ve hizmet sağlayıcılar', content: ['Gerekli olduğu ölçüde bilgiler; yetkili avukatlar, danışmanlar, gayrimenkul uzmanları, mali müşavirler, sigorta şirketleri, teknik hizmet sağlayıcılar, barındırma ve iletişim hizmetleri ile kanunen yetkili kamu kurumlarıyla paylaşılabilir. Kişisel veriler satılmaz.', 'Hizmet sağlayıcılar talimatlarımız doğrultusunda çalışır; gizlilik ve güvenlik tedbirleri uygulanır.'] },
    { title: 'Yurt dışına aktarım', content: ['Barındırma, e-posta, analiz veya form hizmetlerinden bazıları verileri Türkiye dışında işleyebilir. Böyle bir durumda KVKK ve uygulanabilir diğer mevzuatın gerektirdiği güvenlik ve aktarım tedbirleri uygulanır.'] },
    { title: 'Saklama ve güvenlik', content: ['Veriler; toplama amacı, yasal yükümlülükler, mesleki kayıtlar, uyuşmazlık çözümü ve zamanaşımı süreleri için gerekli olduğu kadar saklanır. Erişim kontrolü ve makul teknik/idari tedbirler kullanılır; ancak internet aktarımının tamamen güvenli olduğu garanti edilemez.'] },
    { title: 'Çerezler', content: ['Site; çalışma, dil, tema, güvenlik ve temel analiz için zorunlu çerezler kullanabilir. Çerezleri tarayıcıdan sınırlayabilirsiniz; zorunlu çerezleri engellemek bazı özellikleri etkileyebilir. İsteğe bağlı analiz veya pazarlama araçları, gerekli izinler alınarak kullanılmalıdır.'] },
    { title: 'Haklarınız ve başvurular', content: [`Mevzuatın izin verdiği ölçüde erişim, düzeltme, silme, kısıtlama, itiraz, veri aktarımı veya rızayı geri çekme talebinde bulunabilirsiniz. Talebinizi ${SITE_CONFIG.company.email} adresine gönderin. Kimlik doğrulaması istenebilir. Gerektiğinde yetkili Türk veri koruma kurumlarına başvurabilirsiniz.`] },
    { title: 'Çocuklar ve üçüncü taraf bağlantıları', content: ['Site çocuklara yönelik değildir ve formlar üzerinden çocukların verilerini bilerek toplamıyoruz. LinkedIn, mesajlaşma, ödeme veya diğer sitelere ait bağlantılar kendi politikalarına tabidir.'] },
    { title: 'Değişiklik ve iletişim', content: [`Hizmetlerimiz, teknolojimiz veya hukuki yükümlülüklerimiz değiştiğinde bu politika güncellenebilir. Güncel metin bu sayfada yayımlanır. Gizlilik soruları için ${SITE_CONFIG.company.email} adresine ulaşabilirsiniz.`] },
  ];

  return <LegalDocument title={isEnglish ? 'Privacy Policy' : 'Gizlilik Politikası'} intro={isEnglish ? 'How Asya City collects, uses, protects and shares information across its legal, employment, accident, vehicle, housing and property services.' : 'Asya City\'nin hukuk, iş, kaza, araç, konut ve gayrimenkul hizmetlerinde bilgileri nasıl topladığını, kullandığını, koruduğunu ve paylaştığını açıklar.'} updated="13 September 2026" sections={sections} />;
};

export default Privacy;
