import React from 'react';
import LegalDocument from '../components/common/LegalDocument';
import { SITE_CONFIG } from '../config/site';
import { useTranslation } from '../hooks/useTranslation';

const Terms = () => {
  const { isEnglish } = useTranslation('common');
  const sections = isEnglish ? [
    { title: 'About these terms', content: ['These Terms of Service govern access to the Asya City website and requests made through it. Asya City may coordinate or provide legal, employment, salary, accident, vehicle, housing, property development, purchase, sale and site-management related services in Ankara and throughout Türkiye.', 'Using the website means you accept these terms. If you do not agree, do not use the website or submit a form. A separate written engagement, service agreement, sale contract, property-management agreement or power of attorney may apply to a specific matter and will prevail for that matter.'] },
    { title: 'No automatic lawyer-client relationship', content: ['Submitting a form, sending an email or browsing this website does not create a lawyer-client, consultant-client, agency, brokerage, property-management or other professional relationship. A relationship begins only after written confirmation, conflict checks, agreed scope and any required engagement or power-of-attorney documents.', 'Website content is general information and is not legal advice, an opinion on your case, a valuation, a promise of recovery or a guarantee of a transaction. Do not rely on a page as a substitute for advice about your facts and deadlines.'] },
    { title: 'Service areas', content: ['Possible matters include employment contracts, unpaid salary and benefits, termination and workplace disputes; workplace accidents and occupational safety; vehicle collisions, insurance and compensation issues; home and residential incidents; condominium and site-management matters; and buying, selling, developing or marketing flats and other property.', 'Availability, professional responsibility, licensing, conflict checks, location, evidence, limitation periods and commercial terms are assessed separately for every matter. We may decline a request where we cannot act properly or independently.'] },
    { title: 'User responsibilities', content: ['You must provide accurate, current and complete information, identify urgent deadlines, preserve relevant documents, protect account and contact details, and tell us promptly if information changes. Do not submit unlawful, abusive, malicious, misleading or confidential third-party material without authority.', 'You are responsible for checking translated, automatically completed or uploaded information before submission. A form submission is not proof that documents were received unless we confirm receipt.'] },
    { title: 'Employment, accident and vehicle matters', content: ['For employment, workplace accident, vehicle or other injury matters, preserve medical records, incident reports, photographs, witness details, employment records, insurance information and official correspondence. Do not delay emergency medical care or mandatory reports while waiting for a response from this website.', 'Deadlines and procedural requirements can be strict. We do not promise that a claim is valid, will be accepted, or will succeed until a qualified professional reviews the complete facts and documents.'] },
    { title: 'Documents, petitions and evidence', content: ['You may be asked to provide a petition, court record, accident report, vehicle document, insurance correspondence, photograph or other material relevant to your request. Submit only documents that you are authorised to share and check that the recipient, file and contact details are correct before sending.', 'A website upload or email is not formal service on a court, authority, insurer or opposing party and does not confirm that a filing deadline has been met. Do not send original documents unless we specifically request them, and remove unnecessary identity numbers, signatures, bank details and private information where possible.'] },
    { title: 'Property and housing transactions', content: ['Property development, flat purchase, sale, reservation, brokerage, title-deed, zoning, condominium, construction and handover matters require transaction-specific documents and checks. Advertisements, prices, floor plans, availability, completion dates and investment statements may change and are not binding unless confirmed in a signed agreement.', 'Users should independently verify title, encumbrances, permits, zoning, occupancy, taxes, financing, construction status, condominium records and the identity and authority of every contracting party before paying or signing.'] },
    { title: 'Site and property management', content: ['Site-management information is subject to the management plan, owner or resident decisions, applicable contracts, budgets, technical inspections and Turkish law. Published service descriptions do not guarantee a particular staffing level, repair time, cost, result or availability.', 'Emergency, maintenance, accounting and resident requests should be submitted through the designated channel or directly to the responsible manager when immediate action is required.'] },
    { title: 'Fees and engagement terms', content: ['Fees, commissions, expenses, taxes, payment dates, scope, reporting and termination terms will be stated in the relevant written proposal or agreement. No fee is due solely because a general website page was viewed, but a submitted request may lead to a paid service only after the applicable terms are accepted.'] },
    { title: 'Website use and intellectual property', content: ['You may use the website for lawful personal or business enquiries. You may not copy, scrape, reverse engineer, interfere with, impersonate, overload or introduce malicious code into the website. Text, branding, design, graphics and original materials belong to Asya City or their respective owners and may not be reused without permission.'] },
    { title: 'Third-party services and links', content: ['The website may use third-party hosting, analytics, form delivery, email, messaging, map and social services. Those services have their own terms and privacy policies. We are not responsible for the availability, content, security or practices of an external service that we do not control.'] },
    { title: 'Disclaimers and limitation', content: ['The website is provided on an availability basis. We do not guarantee that it will always be uninterrupted, error-free, current or suitable for a particular decision. To the extent permitted by law, Asya City is not liable for indirect loss, missed deadlines caused by incomplete information, third-party failures or decisions made without professional advice.', 'Nothing in these terms excludes liability that cannot lawfully be excluded or limits mandatory consumer, professional, employment, data-protection or other statutory rights.'] },
    { title: 'Governing law and changes', content: ['These terms are governed by the laws of the Republic of Türkiye. Mandatory jurisdiction and consumer protections remain applicable. We may update these terms by publishing a revised version on this page. For questions, contact us at ' + SITE_CONFIG.company.email + '.'] },
  ] : [
    { title: 'Şartların kapsamı', content: ['Bu Hizmet Şartları Asya City web sitesinin kullanımını ve site üzerinden yapılan talepleri düzenler. Asya City Ankara ve Türkiye genelinde hukuk, iş ve ücret, kaza, araç, konut, gayrimenkul geliştirme, alım-satım ve site yönetimiyle ilgili hizmetleri koordine edebilir veya sunabilir.', 'Siteyi kullanmanız bu şartları kabul ettiğiniz anlamına gelir. Belirli bir iş için ayrıca imzalanan vekaletname, hizmet, satış, aracılık veya site yönetimi sözleşmesi varsa o iş bakımından öncelikle o sözleşme uygulanır.'] },
    { title: 'Otomatik avukat-müvekkil ilişkisi kurulmaz', content: ['Form göndermek, e-posta yazmak veya siteyi ziyaret etmek avukat-müvekkil, danışman-müşteri, acente, emlak aracılığı veya profesyonel hizmet ilişkisi kurmaz. İlişki; yazılı teyit, uygunluk ve çıkar çatışması kontrolü, kapsam mutabakatı ve gerekli sözleşme veya vekaletname sonrasında başlar.', 'Site içerikleri genel bilgilendirmedir; hukuki görüş, dosyanız hakkında sonuç, değerleme, tahsilat vaadi veya işlem garantisi değildir. Somut olay ve süreler için profesyonel inceleme gerekir.'] },
    { title: 'Hizmet alanları', content: ['İş sözleşmeleri, ödenmeyen ücret ve haklar, fesih ve iş uyuşmazlıkları; iş kazaları ve iş sağlığı güvenliği; araç kazaları, sigorta ve tazminat; konut ve ev olayları; kat mülkiyeti ve site yönetimi; daire ve gayrimenkul geliştirme, alım-satım ve pazarlama konuları değerlendirilebilir.', 'Her iş için uygunluk, yetki, çıkar çatışması, delil, süre, bölge ve ticari şartlar ayrıca incelenir. Uygun ve bağımsız şekilde hareket edemediğimiz talepleri reddedebiliriz.'] },
    { title: 'Kullanıcının sorumlulukları', content: ['Doğru ve güncel bilgi vermek, acil süreleri bildirmek, belgeleri korumak, bilgileri değiştiğinde haber vermek ve üçüncü kişilere ait gizli verileri yetkisiz paylaşmamak kullanıcının sorumluluğundadır.', 'Çeviri, otomatik doldurma veya yüklenen bilgileri göndermeden önce kontrol edin. Form gönderilmesi, tarafımızca alındığı teyit edilmedikçe belgelerin teslim edildiği anlamına gelmez.'] },
    { title: 'İş, kaza ve araç dosyaları', content: ['İş, iş kazası, araç veya yaralanma dosyalarında sağlık kayıtları, olay tutanakları, fotoğraflar, tanıklar, iş kayıtları, sigorta bilgileri ve resmi yazışmalar korunmalıdır. Acil sağlık hizmetini veya zorunlu bildirimleri site yanıtını bekleyerek geciktirmeyin.', 'Süreler ve usuller önemli olabilir. Yetkili profesyonel tüm olay ve belgeleri incelemeden bir talebin geçerli, kabul edilebilir veya başarılı olacağı söylenemez.'] },
    { title: 'Belgeler, dilekçeler ve deliller', content: ['Talebinizle ilgili dilekçe, mahkeme belgesi, kaza tutanağı, araç belgesi, sigorta yazışması, fotoğraf veya başka bir materyal istenebilir. Yalnızca paylaşmaya yetkili olduğunuz belgeleri gönderin ve göndermeden önce alıcı, dosya ve iletişim bilgilerinin doğru olduğunu kontrol edin.', 'Siteye yüklenen veya e-postayla gönderilen belge; mahkemeye, kuruma, sigorta şirketine veya karşı tarafa usulüne uygun tebligat anlamına gelmez ve başvuru süresinin korunduğunu göstermez. Özellikle istenmedikçe asıl belge göndermeyin; mümkünse gereksiz kimlik numarası, imza, banka bilgisi ve özel bilgileri karartın.'] },
    { title: 'Gayrimenkul ve konut işlemleri', content: ['Gayrimenkul geliştirme, daire alım-satımı, rezervasyon, tapu, imar, kat mülkiyeti, inşaat ve teslim konuları işlem özelinde belge ve kontrol gerektirir. İlan, fiyat, plan, stok, teslim tarihi ve yatırım ifadeleri imzalı sözleşme ile teyit edilmedikçe bağlayıcı değildir.', 'Ödeme veya imza öncesinde tapu, takyidat, ruhsat, imar, iskan, vergi, finansman, inşaat durumu, kat mülkiyeti kayıtları ve tarafların yetkisi bağımsız olarak kontrol edilmelidir.'] },
    { title: 'Site ve mülk yönetimi', content: ['Site yönetimi; yönetim planı, kat malikleri veya sakin kararları, sözleşmeler, bütçeler, teknik kontroller ve Türk hukukuna tabidir. Hizmet tanımları belirli personel sayısı, onarım süresi, maliyet, sonuç veya sürekli erişim garantisi vermez.', 'Acil bakım ve güvenlik konularında belirlenen sorumlu yöneticiye veya acil hizmetlere doğrudan ulaşılmalıdır.'] },
    { title: 'Ücret ve sözleşme şartları', content: ['Ücret, komisyon, gider, vergi, ödeme, kapsam, raporlama ve sona erme şartları ilgili teklif veya sözleşmede yazılır. Genel bir sayfanın görüntülenmesi tek başına ücret doğurmaz; ücretli hizmet ancak ilgili şartlar kabul edildikten sonra başlar.'] },
    { title: 'Site kullanımı ve fikri haklar', content: ['Site yalnızca hukuka uygun talepler için kullanılabilir. Kopyalama, veri çekme, tersine mühendislik, sistemi bozma, kimliğe bürünme veya zararlı kod gönderme yasaktır. Metin, marka, tasarım ve özgün içerikler Asya City veya hak sahiplerine aittir.'] },
    { title: 'Üçüncü taraf hizmetler', content: ['Site; barındırma, analiz, form, e-posta, mesajlaşma, harita ve sosyal medya hizmetlerini kullanabilir. Bu hizmetlerin kendi şartları ve gizlilik politikaları vardır. Kontrolümüz dışındaki hizmetlerin güvenliği veya sürekliliğinden sorumlu değiliz.'] },
    { title: 'Sorumluluk sınırı', content: ['Site erişilebilirlik esasına göre sunulur; kesintisiz, hatasız, güncel veya belirli bir karara uygun olduğu garanti edilmez. Kanunen izin verilen ölçüde dolaylı zararlar, eksik bilgi nedeniyle kaçırılan süreler, üçüncü taraf arızaları veya profesyonel görüş alınmadan verilen kararlar bakımından sorumluluk doğmaz.', 'Kanunen sınırlandırılamayan sorumluluklar ve tüketici, meslek, iş ve veri koruma hakları saklıdır.'] },
    { title: 'Uygulanacak hukuk ve değişiklikler', content: ['Bu şartlar Türkiye Cumhuriyeti hukukuna tabidir. Zorunlu yetki ve tüketici hakları saklıdır. Şartlar bu sayfada yayımlanarak güncellenebilir. Sorularınız için ' + SITE_CONFIG.company.email + ' adresine ulaşabilirsiniz.'] },
  ];

  return <LegalDocument title={isEnglish ? 'Terms of Service' : 'Hizmet Şartları'} intro={isEnglish ? 'The rules for using the Asya City website and requesting legal, property, employment, accident, vehicle and site-management services.' : 'Asya City web sitesinin ve hukuk, gayrimenkul, iş, kaza, araç ve site yönetimi hizmet taleplerinin kullanım kuralları.'} updated="13 September 2026" sections={sections} />;
};

export default Terms;
