const en = {
  header: {
    home: 'Home', services: 'Services', whyProfessional: 'Why Professional?', howItWorks: 'How It Works', pricing: 'Pricing', about: 'About', corporate: 'Corporate', management: 'Site Management', blog: 'Blog', references: 'References', contact: 'Contact', application: 'Apply', contactButton: 'Contact', getQuote: 'Get a Quote'
  },
  references: {
    eyebrow: 'OUR REFERENCES',
    title: 'Projects We Proudly Serve',
    subtitle: 'As Asya City, we provide management services for sites, apartments, and collective living spaces with a transparent and sustainable approach.',
    searchPlaceholder: 'Search project or location...',
    allCategories: 'All',
    sites: 'Sites & Residences',
    apartments: 'Apartments',
    villas: 'Villas',
    noResults: 'No references found matching your search criteria.'
  },
  footer: {
    company: 'Asya City Professional Site Management', tagline: 'Peace, transparency and confidence in your living space.', quickLinks: 'Quick Links', services: 'Our Services', contactInfo: 'Contact Information', phone: 'Phone', email: 'Email', address: 'Address', workingHours: 'Working Hours', monFri: 'Mon-Fri: 09:00 - 18:00', sat: 'Sat: 10:00 - 14:00', sun: 'Sun: Closed', allRights: 'All rights reserved.', privacy: 'Privacy Policy', terms: 'Terms of Service'
  },
  forms: {
    fullName: 'Full Name', email: 'Email', phone: 'Phone', subject: 'Subject', message: 'Message', submit: 'Send', required: 'This field is required', invalidEmail: 'Please enter a valid email address', success: 'Your message has been sent successfully.', error: 'An error occurred. Please try again.'
  },
  contact: { title: 'Contact Us', subtitle: 'Let us find the right management model for your site.', formTitle: 'Contact form', name: 'Full name', email: 'Email', phone: 'Phone', site: 'Site or apartment name', message: 'Your message', submit: 'Send message', success: 'Your message has been received. We will get back to you shortly.', address: 'Ankara, Türkiye', hours: 'Mon-Fri: 09:00 - 18:00' },
  applications: { title: 'Applications', subtitle: 'Choose the form that fits your needs and send your request.', site: { title: 'Site Quote Form', description: 'Request a complete management proposal for your apartment or site.', name: 'Full name', siteName: 'Site / apartment name', blocks: 'Number of blocks', address: 'Site address', units: 'Number of apartments', offices: 'Number of offices', shops: 'Number of shops', phone: 'Phone', email: 'Email', message: 'Your message', heating: 'Heating system', management: 'How is your site or apartment currently managed?', services: ['Cleaning staff', 'Security staff', 'Caretaker', 'Elevator', 'Pool maintenance', 'Garden maintenance'], yes: 'Yes', no: 'No', managementOptions: ['An owner is elected every year', 'We have a professional manager but want to change', 'Our site is new and has no manager yet'], sections: { personal: 'Personal Information', site: 'Apartment / Site Information', services: 'Staff / Service Status', management: 'Heating and Management Information' }, submit: 'Submit form', success: 'Your application has been received. Our team will contact you shortly.' }, career: { title: 'Human Resources Application Form', description: 'Share your details if you would like to join the Asya City team.', sections: { personal: '01. Personal Information', contact: '02. Contact Information', education: '03. Education Information', computer: '04. Computer Skills', languages: '05. Foreign Language Skills', experience: '06. Work Experience', references: '07. References', other: '08. Other Information', declaration: 'Declaration and Approval' }, fields: { identity: 'National ID number', name: 'Full name', gender: 'Gender', marital: 'Marital status', nationality: 'Nationality', birthPlace: 'Place of birth', birthDate: 'Date of birth', blood: 'Blood type', license: 'Driving licence (date and class)', smoking: 'Do you smoke?', military: 'Military status', photo: 'Photo (JPG/PNG, max 2 MB)', mobile: 'Mobile phone', email: 'Email address', homePhone: 'Home phone', address: 'Address', last: 'Most recent school', previous: 'Previous school', schoolType: 'School type', schoolName: 'School name', startYear: 'Start year', endYear: 'End year', department: 'Department', grade: 'Diploma grade / score', program: 'Program name', level: 'Skill level', languages: ['English', 'German', 'French', 'Greek', 'Russian', 'Other language'], workplace: 'Workplace name', role: 'Role', reference: 'Full name', profession: 'Profession', phone: 'Phone', clubs: 'Clubs and associations', hobbies: 'Hobbies and interests', declaration: 'I confirm that the information provided above is accurate and accept responsibility for any issues caused by incorrect information.' }, submit: 'Submit form', success: 'Your application has been received. We will contact you when a suitable position is available.' } },
  servicePages: { ctaTitle: 'Choose the right management model for your site.', ctaText: 'Let us review your current operation and prepare a transparent proposal.', consulting: { title: 'Professional Site Consulting', intro: 'Compliant, practical advice for boards and residents.', points: ['Management-plan review', 'Assembly support', 'Operational roadmap'] }, security: { title: 'Site Security Services', intro: 'A planned and accountable security operation for your shared space.', points: ['Staff planning', 'Entry control', 'Incident tracking'] }, legal: { title: 'Site Legal Services', intro: 'Expert support for condominium law and management decisions.', points: ['Decision processes', 'Contract review', 'Dispute prevention'] }, staff: { title: 'Site Staff Services', intro: 'Manage recruitment, shifts and performance from one place.', points: ['Recruitment support', 'Shift planning', 'Performance tracking'] }, accounting: { title: 'Accounting and Dues Tracking', intro: 'Follow every financial movement from budget to collection.', points: ['Dues tracking', 'Budget preparation', 'Monthly reporting'] }, technical: { title: 'Site Technical Services', intro: 'Keep maintenance, inspections and repairs on one reliable schedule.', points: ['Planned maintenance', 'Repair coordination', 'Supplier management'] }, cleaning: { title: 'Site Cleaning Services', intro: 'Keep shared spaces healthy with consistent teams and checklists.', points: ['Daily cleaning', 'Shared-space checks', 'Hygiene planning'] }, pool: { title: 'Site Pool Maintenance', intro: 'Keep pools safe, hygienic and ready throughout the season.', points: ['Water testing', 'Equipment checks', 'Season preparation'] }, landscape: { title: 'Garden and Landscape Services', intro: 'Care for green spaces with seasonal planning and sustainable maintenance.', points: ['Pruning and care', 'Irrigation tracking', 'Seasonal planning'] } },
  hero: {
    eyebrow: 'Professional property management', title: 'A better management system for the place you call home.', subtitle: 'We bring dues, maintenance, budgets and communication into one clear operating system, giving boards control and residents confidence.', primaryCta: 'Request a free assessment', secondaryCta: 'Explore our services', stats: { sites: 'Sites managed', experience: 'Years of experience', satisfaction: 'Resident satisfaction', support: 'Emergency support' }
  },
  benefits: {
    title: 'The details that make management better', subtitle: 'An intentional operating model designed for clearer decisions, calmer communication and healthier shared spaces.', items: [
      { title: 'Transparent budgets', description: 'Make income, spending and decisions easy to understand with clear monthly reporting.' },
      { title: 'Planned maintenance', description: 'Track schedules, suppliers and inspections before small issues become expensive repairs.' },
      { title: 'Resident communication', description: 'Create channels where requests reach the right person and every outcome can be seen.' },
      { title: 'Legal confidence', description: 'Move forward with expert support aligned with condominium law and your management plan.' }
    ]
  },
  departments: {
    title: 'Every part of site life, under one roof', subtitle: 'A complete management service that connects administrative, financial, technical and resident needs.', finance: { title: 'Finance and accounting', description: 'Dues tracking, budget planning, invoices and monthly financial reporting.' }, technical: { title: 'Technical maintenance', description: 'Consistent oversight of shared spaces, systems and urgent repairs.' }, communication: { title: 'Resident relations', description: 'Timely, understandable communication for requests, notices and decisions.' }, legal: { title: 'Legal and administration', description: 'Confident handling of assemblies, contracts and management-plan processes.' }
  },
  process: { title: 'How we start working together', subtitle: 'Five clear, measurable steps from the first conversation to everyday management.', steps: [
    { title: 'Talk to us', description: 'Tell us what is happening and let us schedule a short discovery call.' }, { title: 'Assess the site', description: 'Review the current budget, technical condition and open issues together.' }, { title: 'Build the proposal', description: 'Receive a transparent proposal with a clear scope and responsibilities.' }, { title: 'Present to the assembly', description: 'Share the plan with owners using straightforward, useful information.' }, { title: 'Take over management', description: 'Begin with scheduled reporting and consistent on-site follow-up.' }
  ] },
  technology: { title: 'Management that stays visible', subtitle: 'Digital tools bring payments, requests and notices into one simple flow.', features: [
    { title: 'Mobile access', description: 'Reach your site updates and notices wherever you are.' }, { title: 'Online payments', description: 'Follow dues and shared expenses securely.' }, { title: 'Management dashboard', description: 'See budgets, work orders and reports in one place.' }, { title: 'Request tracking', description: 'Follow the status and outcome of every maintenance request.' }
  ] },
  trust: { eyebrow: 'The difference is operational', title: 'Good management makes daily life feel lighter.', description: 'When budgets, repairs and decisions have a clear owner, residents spend less energy chasing answers and more time enjoying their home.', link: 'Why professional management?', items: ['Clear monthly reporting', 'Planned maintenance', 'Calmer communication', 'Legal confidence'], faqEyebrow: 'Questions, answered', faqTitle: 'A clearer way to choose your manager.', faqs: [
    { question: 'What does a professional site manager handle?', answer: 'We coordinate financial, technical, legal and resident-relations work as one accountable operating system.' }, { question: 'Can you take over an existing site?', answer: 'Yes. We begin with a practical handover review, identify open issues and prepare a transparent transition plan.' }, { question: 'How do residents see financial information?', answer: 'Regular reports, planned budgets and clear payment records make the operating picture easy to follow.' }
  ], ctaEyebrow: 'Start with a conversation', ctaTitle: 'Bring clarity to your site.', ctaButton: 'Request a conversation' }
};

export default en;
