const tr = {
  header: {
    home: 'Ana Sayfa', services: 'Hizmetlerimiz', whyProfessional: 'Neden Profesyonel?', howItWorks: 'Nasıl Çalışır?', pricing: 'Fiyatlandırma', about: 'Hakkımızda', corporate: 'Kurumsal', management: 'Site Yönetimi', blog: 'Blog', references: 'Referanslar', contact: 'İletişim', application: 'Başvuru', contactButton: 'İletişim', getQuote: 'Teklif Al'
  },
  references: {
    eyebrow: 'REFERANSLARIMIZ',
    title: 'Güvenle hizmet verdiğimiz projeler',
    subtitle: 'Asya City olarak site, apartman ve toplu yaşam alanlarında düzenli, şeffaf ve sürdürülebilir yönetim anlayışıyla hizmet sunuyoruz.',
    searchPlaceholder: 'Proje, dosya veya ilçe ara...',
    allCategories: 'Tümü',
    sites: 'Siteler & Konutlar',
    apartments: 'Apartmanlar',
    villas: 'Villalar',
    employment: 'İş ve Ücret Uyuşmazlıkları',
    noResults: 'Aradığınız kriterlere uygun referans bulunamadı.'
  },
  footer: {
    company: 'Asya City Profesyonel Site Yönetimi', tagline: 'Yaşam alanlarınızda huzur, şeffaflık ve güven.', quickLinks: 'Hızlı Bağlantılar', services: 'Hizmetlerimiz', contactInfo: 'İletişim Bilgileri', phone: 'Telefon', email: 'E-posta', address: 'Adres', workingHours: 'Çalışma Saatleri', monFri: 'Pzt-Cum: 09:00 - 18:00', sat: 'Cmt: 10:00 - 14:00', sun: 'Paz: Kapalı', allRights: 'Tüm hakları saklıdır.', privacy: 'Gizlilik Politikası', terms: 'Kullanım Şartları'
  },
  forms: {
    fullName: 'Ad Soyad', email: 'E-posta', phone: 'Telefon', subject: 'Konu', message: 'Mesaj', submit: 'Gönder', required: 'Bu alan zorunludur', invalidEmail: 'Geçerli bir e-posta adresi girin', success: 'Mesajınız başarıyla gönderildi.', error: 'Bir hata oluştu. Lütfen tekrar deneyin.'
  },
  contact: { title: 'Bize Ulaşın', subtitle: 'Siteniz için doğru yönetim modelini birlikte konuşalım.', formTitle: 'İletişim formu', name: 'Ad Soyad', email: 'E-posta', phone: 'Telefon', site: 'Site veya apartman adı', message: 'Mesajınız', submit: 'Gönder', success: 'Mesajınız alındı. En kısa sürede size dönüş yapacağız.', address: 'Ankara, Türkiye', hours: 'Pzt-Cum: 09:00 - 18:00' },
  applications: { title: 'Başvuru', subtitle: 'İhtiyacınıza uygun formu seçerek başvurunuzu iletin.', site: { title: 'Site Teklif Formu', description: 'Apartman veya siteniz için kapsamlı bir yönetim teklifi alın.', name: 'Adınız Soyadınız', siteName: 'Site / apartman adı', blocks: 'Blok sayısı', address: 'Site adresi', units: 'Daire sayısı', offices: 'Ofis sayısı', shops: 'Dükkan sayısı', phone: 'Telefon', email: 'E-posta', message: 'Mesajınız', heating: 'Isınma sistemi', management: 'Site / apartmanınız nasıl yönetiliyor?', services: ['Temizlik görevlisi', 'Güvenlik görevlisi', 'Kapıcı', 'Asansör', 'Havuz bakım hizmeti', 'Bahçe bakım hizmeti'], yes: 'Var', no: 'Yok', managementOptions: ['Her yıl maliklerden biri seçiliyor', 'Profesyonel yöneticimiz var ancak değiştirmek istiyoruz', 'Sitemiz yeni, henüz yöneticimiz yok'], sections: { personal: 'Kişisel Bilgiler', site: 'Apartman / Site Bilgileri', services: 'Personel / Hizmet Durumu', management: 'Isınma ve Yönetim Bilgileri' }, submit: 'Formu gönder', success: 'Başvurunuz alındı. Ekibimiz kısa süre içinde sizinle iletişime geçecek.' }, career: { title: 'İnsan Kaynakları Başvuru Formu', description: 'Asya City ekibine katılmak için bilgilerinizi paylaşın.', sections: { personal: '01. Kişisel Bilgiler', contact: '02. İletişim Bilgileri', education: '03. Eğitim Bilgileri', computer: '04. Bilgisayar Bilgileri', languages: '05. Yabancı Dil Bilgileri', experience: '06. İş Deneyimi', references: '07. Referanslar', other: '08. Diğer Bilgiler', declaration: 'Beyan ve Onay' }, fields: { identity: 'TC Kimlik Numarası', name: 'Adı Soyadı', gender: 'Cinsiyeti', marital: 'Medeni Durumu', nationality: 'Uyruğu', birthPlace: 'Doğum Yeri', birthDate: 'Doğum Tarihi', blood: 'Kan Grubu', license: 'Ehliyet (Tarihi ve Sınıfı)', smoking: 'Sigara İçiyor mu?', military: 'Askerlik Durumu', photo: 'Fotoğraf (JPG/PNG, max 2 MB)', mobile: 'Cep Telefonu', email: 'E-Posta Adresi', homePhone: 'Ev Telefonu', address: 'Adresi', last: 'Son bitirilen okul', previous: 'Bir önceki mezun olunan okul', schoolType: 'Okul Türü', schoolName: 'Okul Adı', startYear: 'Başlama Yılı', endYear: 'Bitirme Yılı', department: 'Bölüm', grade: 'Diploma Derecesi / Notu', program: 'Program Adı', level: 'Kullanım Derecesi', languages: ['İngilizce', 'Almanca', 'Fransızca', 'Rumca', 'Rusça', 'Diğer dil'], workplace: 'İşyeri Adı', role: 'Görevi', reference: 'Adı Soyadı', profession: 'Mesleği', phone: 'Telefonu', clubs: 'Üye Olunan Kulüp ve Dernekler', hobbies: 'Hobiler ve İlgi Alanları', declaration: 'Yukarıda verdiğim bilgilerin doğru olduğunu ve yanlış bilgilerden doğabilecek tüm sorunlardan sorumlu olduğumu kabul ediyorum.' }, submit: 'Formu gönder', success: 'Başvurunuz alındı. Uygun bir pozisyon olduğunda sizinle iletişime geçeceğiz.' } },
  servicePages: { ctaTitle: 'Siteniz için doğru yönetim modelini seçin.', ctaText: 'Mevcut durumunuzu birlikte inceleyelim ve şeffaf bir teklif hazırlayalım.', consulting: { title: 'Profesyonel Site Danışmanlık Hizmetleri', intro: 'Yönetim kurulları ve site sakinleri için mevzuata uygun, çözüm odaklı danışmanlık.', points: ['Yönetim planı incelemesi', 'Genel kurul danışmanlığı', 'Operasyonel yol haritası'] }, security: { title: 'Site Güvenlik Hizmetleri', intro: 'Yaşam alanınızı koruyan planlı ve denetlenebilir güvenlik operasyonu.', points: ['Personel planlaması', 'Giriş çıkış kontrolü', 'Risk ve olay takibi'] }, legal: { title: 'Site Hukuk Hizmetleri', intro: 'Kat Mülkiyeti Kanunu ve yönetim süreçleri için uzman hukuki destek.', points: ['Karar süreçleri', 'Sözleşme kontrolü', 'Uyuşmazlık önleme'] }, staff: { title: 'Site Personel Hizmetleri', intro: 'Site personelinin seçimi, vardiyası ve performansını tek merkezden yönetin.', points: ['İşe alım desteği', 'Vardiya planı', 'Performans takibi'] }, accounting: { title: 'Muhasebe ve Aidat Takip Hizmetleri', intro: 'Bütçeden tahsilata kadar tüm mali hareketleri anlaşılır raporlarla izleyin.', points: ['Aidat takibi', 'Bütçe hazırlığı', 'Aylık raporlama'] }, technical: { title: 'Site Teknik Hizmetleri', intro: 'Bakım, kontrol ve arıza süreçlerini kesintisiz bir teknik takvimle yönetin.', points: ['Periyodik bakım', 'Arıza koordinasyonu', 'Tedarikçi yönetimi'] }, cleaning: { title: 'Site Temizlik Hizmetleri', intro: 'Ortak alanların hijyenini düzenli ekip ve kontrol listeleriyle koruyun.', points: ['Günlük temizlik', 'Ortak alan kontrolü', 'Hijyen planı'] }, pool: { title: 'Site Havuz Bakım Hizmetleri', intro: 'Havuzların güvenli, hijyenik ve sezon boyunca kullanıma hazır kalmasını sağlayın.', points: ['Su analizleri', 'Ekipman kontrolü', 'Sezon hazırlığı'] }, landscape: { title: 'Bahçe Bakımı ve Peyzaj Hizmetleri', intro: 'Yeşil alanları mevsimsel bakım ve sürdürülebilir peyzaj planıyla yaşatın.', points: ['Budama ve bakım', 'Sulama takibi', 'Mevsimsel planlama'] } },
  hero: {
    eyebrow: 'Profesyonel site yönetimi', title: 'Yaşam alanınız için daha iyi bir yönetim sistemi.', subtitle: 'Aidat, bakım, bütçe ve iletişim süreçlerini tek merkezden yönetiyor; yöneticilere kontrol, sakinlere güven veriyoruz.', primaryCta: 'Ücretsiz keşif isteyin', secondaryCta: 'Hizmetleri keşfedin', stats: { sites: 'Yönetilen site', experience: 'Yıllık deneyim', satisfaction: 'Sakin memnuniyeti', support: 'Acil destek' }
  },
  benefits: {
    title: 'Yönetimde fark yaratan detaylar', subtitle: 'Proyontech yaklaşımından ilham alan, Asya City için tasarlanmış daha düzenli ve görünür bir işletim modeli.', items: [
      { title: 'Şeffaf bütçe', description: 'Gelir, gider ve kararları herkesin anlayabileceği aylık raporlarla görünür kılıyoruz.' },
      { title: 'Planlı bakım', description: 'Arıza çıkmasını beklemeden bakım takvimini, tedarikçileri ve kontrolleri takip ediyoruz.' },
      { title: 'Sakin iletişimi', description: 'Taleplerin kaybolmadığı, doğru kişiye ulaştığı ve sonucu görülen iletişim kanalları kuruyoruz.' },
      { title: 'Hukuki güven', description: 'Kat Mülkiyeti Kanunu ve yönetim planına uygun karar süreçleri için uzman desteği sağlıyoruz.' }
    ]
  },
  departments: {
    title: 'Site yaşamının tüm başlıkları tek çatı altında', subtitle: 'İdari, mali, teknik ve iletişim süreçlerini birlikte ele alan eksiksiz yönetim hizmeti.', finance: { title: 'Finans ve muhasebe', description: 'Aidat takibi, bütçe planı, fatura ve aylık mali raporlama.' }, technical: { title: 'Teknik bakım', description: 'Ortak alan, mekanik sistem ve acil arıza süreçlerinin düzenli takibi.' }, communication: { title: 'Sakin ilişkileri', description: 'Talepler, duyurular ve kararların zamanında, anlaşılır iletişimi.' }, legal: { title: 'Hukuki ve idari işler', description: 'Genel kurul, sözleşme ve yönetim planı süreçlerinde güvenli ilerleme.' }
  },
  process: { title: 'Birlikte çalışmaya nasıl başlıyoruz?', subtitle: 'İlk görüşmeden düzenli yönetime kadar açık ve ölçülebilir beş adım.', steps: [
    { title: 'Bize ulaşın', description: 'İhtiyaçlarınızı dinleyelim ve kısa bir ön görüşme planlayalım.' }, { title: 'Site analizi', description: 'Mevcut bütçeyi, teknik durumu ve açık işleri birlikte inceleyelim.' }, { title: 'Şeffaf teklif', description: 'Kapsamı ve sorumlulukları net, karşılaştırılabilir bir teklif sunalım.' }, { title: 'Genel kurul', description: 'Planı kat maliklerine anlaşılır verilerle aktaralım.' }, { title: 'Yönetimi devralalım', description: 'Takvimli raporlama ve düzenli saha takibiyle başlayalım.' }
  ] },
  technology: { title: 'Yönetim, herkes için daha görünür', subtitle: 'Dijital araçlarla ödeme, talep ve duyuruları tek bir akışta buluşturuyoruz.', features: [
    { title: 'Mobil erişim', description: 'Site gündemine ve duyurulara her yerden ulaşın.' }, { title: 'Online ödeme', description: 'Aidat ve ortak gider ödemelerini güvenle takip edin.' }, { title: 'Yönetim paneli', description: 'Bütçe, iş emri ve raporları tek ekranda görün.' }, { title: 'Talep takibi', description: 'Bakım taleplerinin durumunu ve sonucunu izleyin.' }
  ] },
  trust: { eyebrow: 'Fark, işleyişte ortaya çıkar', title: 'İyi yönetim, günlük hayatı hafifletir.', description: 'Bütçelerin, bakımların ve kararların net bir sorumlusu olduğunda sakinler cevap aramakla daha az, yaşam alanlarının keyfini çıkarmakla daha çok ilgilenir.', link: 'Neden profesyonel yönetim?', items: ['Anlaşılır aylık raporlar', 'Planlı bakım takvimi', 'Daha sakin iletişim', 'Yasal güven'], faqEyebrow: 'Merak edilenler', faqTitle: 'Yönetim şirketinizi seçmenin daha net yolu.', faqs: [
    { question: 'Profesyonel site yönetimi neleri kapsar?', answer: 'Finans, teknik, yasal süreçler ve sakin iletişimini tek bir sorumluluk sistemi içinde koordine ediyoruz.' }, { question: 'Mevcut bir sitenin yönetimini devralabilir misiniz?', answer: 'Evet. Önce mevcut durumu ve açık işleri inceliyor, ardından şeffaf bir devir planı hazırlıyoruz.' }, { question: 'Sakinler mali bilgileri nasıl takip eder?', answer: 'Düzenli raporlar, planlı bütçeler ve anlaşılır ödeme kayıtlarıyla yönetimin fotoğrafı herkes için görünür olur.' }
  ], ctaEyebrow: 'Bir görüşmeyle başlayalım', ctaTitle: 'Sitenize netlik kazandırın.', ctaButton: 'Görüşme talep edin' }
};

export default tr;
