const tr = {
  header: {
    home: 'Ana Sayfa', services: 'Hizmetlerimiz', whyProfessional: 'Neden Biz?', howItWorks: 'Nasıl Çalışır?', pricing: 'Fiyatlandırma', about: 'Hakkımızda', corporate: 'Kurumsal', management: 'Site Yönetimi', blog: 'Blog', references: 'Referanslar', contact: 'İletişim', application: 'Başvuru', contactButton: 'İletişim', getQuote: 'Teklif Al'
  },
  references: {
    eyebrow: 'REFERANSLARIMIZ',
    title: 'Güvenle hizmet verdiğimiz projeler',
    subtitle: 'Asya City olarak site, apartman ve toplu yaşam alanlarında düzenli, şeffaf ve sürdürülebilir yönetim anlayışıyla hizmet sunuyoruz.',
    searchPlaceholder: 'Proje, dosya veya ilçe ara...',
    allCategories: 'Tümü',
    sites: 'Siteler & Konutlar',
    apartments: 'Apartmanlar',
    villas: 'Villalar',
    employment: 'İş ve Ücret Uyuşmazlıkları',
    noResults: 'Aradığınız kriterlere uygun referans bulunamadı.'
  },
  footer: {
    company: 'Asya City Profesyonel Site Yönetimi', tagline: 'Yaşam alanlarınızda huzur, şeffaflık ve güven.', quickLinks: 'Hızlı Bağlantılar', services: 'Hizmetlerimiz', contactInfo: 'İletişim Bilgileri', phone: 'Telefon', email: 'E-posta', address: 'Adres', workingHours: 'Çalışma Saatleri', monFri: 'Pzt-Cum: 09:00 - 18:00', sat: 'Cmt: 10:00 - 14:00', sun: 'Paz: Kapalı', allRights: 'Tüm hakları saklıdır.', privacy: 'Gizlilik Politikası', terms: 'Kullanım Şartları'
  },
  forms: {
    fullName: 'Ad Soyad', email: 'E-posta', phone: 'Telefon', subject: 'Konu', message: 'Mesaj', submit: 'Gönder', required: 'Bu alan zorunludur', invalidEmail: 'Geçerli bir e-posta adresi girin', success: 'Mesajınız başarıyla gönderildi.', error: 'Bir hata oluştu. Lütfen tekrar deneyin.'
  },
  contact: { title: 'Bize Ulaşın', subtitle: 'Siteniz için doğru yönetim modelini birlikte konuşalım.', formTitle: 'İletişim formu', name: 'Ad Soyad', email: 'E-posta', phone: 'Telefon', site: 'Site veya apartman adı', message: 'Mesajınız', submit: 'Gönder', success: 'Mesajınız alındı. En kısa sürede size dönüş yapacağız.', address: 'Ankara, Türkiye', hours: 'Pzt-Cum: 09:00 - 18:00' },
  applications: { title: 'Başvuru', subtitle: 'İhtiyacınıza uygun formu seçerek başvurunuzu iletin.', site: { title: 'Site Teklif Formu', description: 'Apartman veya siteniz için kapsamlı bir yönetim teklifi alın.', name: 'Adınız Soyadınız', siteName: 'Site / apartman adı', blocks: 'Blok sayısı', address: 'Site adresi', units: 'Daire sayısı', offices: 'Ofis sayısı', shops: 'Dükkan sayısı', phone: 'Telefon', email: 'E-posta', message: 'Mesajınız', heating: 'Isınma sistemi', management: 'Site / apartmanınız nasıl yönetiliyor?', services: ['Temizlik görevlisi', 'Güvenlik görevlisi', 'Kapıcı', 'Asansör', 'Havuz bakım hizmeti', 'Bahçe bakım hizmeti'], yes: 'Var', no: 'Yok', managementOptions: ['Her yıl maliklerden biri seçiliyor', 'Profesyonel yöneticimiz var ancak değiştirmek istiyoruz', 'Sitemiz yeni, henüz yöneticimiz yok'], sections: { personal: 'Kişisel Bilgiler', site: 'Apartman / Site Bilgileri', services: 'Personel / Hizmet Durumu', management: 'Isınma ve Yönetim Bilgileri' }, submit: 'Formu gönder', success: 'Başvurunuz alındı. Ekibimiz kısa süre içinde sizinle iletişime geçecek.' }, career: { title: 'İnsan Kaynakları Başvuru Formu', description: 'Asya City ekibine katılmak için bilgilerinizi paylaşın.', sections: { personal: '01. Kişisel Bilgiler', contact: '02. İletişim Bilgileri', education: '03. Eğitim Bilgileri', computer: '04. Bilgisayar Bilgileri', languages: '05. Yabancı Dil Bilgileri', experience: '06. İş Deneyimi', references: '07. Referanslar', other: '08. Diğer Bilgiler', declaration: 'Beyan ve Onay' }, fields: { identity: 'TC Kimlik Numarası', name: 'Adı Soyadı', gender: 'Cinsiyeti', marital: 'Medeni Durumu', nationality: 'Uyruğu', birthPlace: 'Doğum Yeri', birthDate: 'Doğum Tarihi', blood: 'Kan Grubu', license: 'Ehliyet (Tarihi ve Sınıfı)', smoking: 'Sigara İçiyor mu?', military: 'Askerlik Durumu', photo: 'Fotoğraf (JPG/PNG, max 2 MB)', mobile: 'Cep Telefonu', email: 'E-Posta Adresi', homePhone: 'Ev Telefonu', address: 'Adresi', last: 'Son bitirilen okul', previous: 'Bir önceki mezun olunan okul', schoolType: 'Okul Türü', schoolName: 'Okul Adı', startYear: 'Başlama Yılı', endYear: 'Bitirme Yılı', department: 'Bölüm', grade: 'Diploma Derecesi / Notu', program: 'Program Adı', level: 'Kullanım Derecesi', languages: ['İngilizce', 'Almanca', 'Fransızca', 'Rumca', 'Rusça', 'Diğer dil'], workplace: 'İşyeri Adı', role: 'Görevi', reference: 'Adı Soyadı', profession: 'Mesleği', phone: 'Telefonu', clubs: 'Üye Olunan Kulüp ve Dernekler', hobbies: 'Hobiler ve İlgi Alanları', declaration: 'Yukarıda verdiğim bilgilerin doğru olduğunu ve yanlış bilgilerden doğabilecek tüm sorunlardan sorumlu olduğumu kabul ediyorum.' }, submit: 'Formu gönder', success: 'Başvurunuz alındı. Uygun bir pozisyon olduğunda sizinle iletişime geçeceğiz.' } },
  servicePages: { ctaTitle: 'Siteniz için doğru yönetim modelini seçin.', ctaText: 'Mevcut durumunuzu birlikte inceleyelim ve şeffaf bir teklif hazırlayalım.', consulting: { title: 'Profesyonel Site Danışmanlık Hizmetleri', intro: 'Yönetim kurulları ve site sakinleri için mevzuata uygun, çözüm odaklı danışmanlık.', points: ['Yönetim planı incelemesi', 'Genel kurul danışmanlığı', 'Operasyonel yol haritası'] }, security: { title: 'Site Güvenlik Hizmetleri', intro: 'Yaşam alanınızı koruyan planlı ve denetlenebilir güvenlik operasyonu.', points: ['Personel planlaması', 'Giriş çıkış kontrolü', 'Risk ve olay takibi'] }, legal: { title: 'Site Hukuk Hizmetleri', intro: 'Kat Mülkiyeti Kanunu ve yönetim süreçleri için uzman hukuki destek.', points: ['Karar süreçleri', 'Sözleşme kontrolü', 'Uyuşmazlık önleme'] }, staff: { title: 'Site Personel Hizmetleri', intro: 'Site personelinin seçimi, vardiyası ve performansını tek merkezden yönetin.', points: ['İşe alım desteği', 'Vardiya planı', 'Performans takibi'] }, accounting: { title: 'Muhasebe ve Aidat Takip Hizmetleri', intro: 'Bütçeden tahsilata kadar tüm mali hareketleri anlaşılır raporlarla izleyin.', points: ['Aidat takibi', 'Bütçe hazırlığı', 'Aylık raporlama'] }, technical: { title: 'Site Teknik Hizmetleri', intro: 'Bakım, kontrol ve arıza süreçlerini kesintisiz bir teknik takvimle yönetin.', points: ['Periyodik bakım', 'Arıza koordinasyonu', 'Tedarikçi yönetimi'] }, cleaning: { title: 'Site Temizlik Hizmetleri', intro: 'Ortak alanların hijyenini düzenli ekip ve kontrol listeleriyle koruyun.', points: ['Günlük temizlik', 'Ortak alan kontrolü', 'Hijyen planı'] }, pool: { title: 'Site Havuz Bakım Hizmetleri', intro: 'Havuzların güvenli, hijyenik ve sezon boyunca kullanıma hazır kalmasını sağlayın.', points: ['Su analizleri', 'Ekipman kontrolü', 'Sezon hazırlığı'] }, landscape: { title: 'Bahçe Bakımı ve Peyzaj Hizmetleri', intro: 'Yeşil alanları mevsimsel bakım ve sürdürülebilir peyzaj planıyla yaşatın.', points: ['Budama ve bakım', 'Sulama takibi', 'Mevsimsel planlama'] } },
  hero: {
    eyebrow: 'Profesyonel site ve bina yönetimi', title: 'Sitenizi şeffaf, profesyonel ve güvenilir bir sistemle yönetiyoruz.', subtitle: 'Mali yönetimden teknik bakıma, personel süreçlerinden hukuki desteğe kadar bina ve sitenizin tüm yönetim ihtiyaçlarını tek merkezden yürütüyoruz.', primaryCta: 'Ücretsiz teklif al', secondaryCta: 'Hizmetlerimizi incele', stats: { sites: 'Şeffaf mali yönetim', experience: 'Hukuki altyapı', satisfaction: 'Hızlı koordinasyon', support: '24 saat içinde dönüş' }
  },
  benefits: {
    title: 'Neden Asya City?', subtitle: 'Yönetim yükünü azaltıyor, yaşam kalitesini yükseltiyoruz.', items: [
      { title: 'Şeffaf ve izlenebilir mali yönetim', description: 'Borç, alacak, gelir-gider hareketleri, faturalar ve raporlar dijital sistem üzerinden düzenli olarak takip edilir.' },
      { title: 'Güçlü hukuki altyapı', description: 'Aidat alacaklarından genel kurul süreçlerine kadar hukuki süreçleri uzman hukukçularla yürütüyoruz.' },
      { title: 'Planlı ve hızlı operasyon', description: 'Teknik bakım, temizlik, güvenlik ve ortak alan taleplerini kayıt altına alıyor, hızlıca koordine ediyoruz.' },
      { title: 'Profesyonel devir teslim', description: 'Belge, hesap, karar ve idari süreçlerin düzenli biçimde devralınmasını sağlıyoruz.' }
    ]
  },
  departments: {
    title: 'Hizmetlerimiz', subtitle: 'İdari, mali, teknik ve ortak yaşam ihtiyaçlarını tek bir profesyonel yönetim modeli içinde bir araya getiriyoruz.', finance: { title: 'Şeffaf mali yönetim ve online işlemler', description: 'Dijital takip, güvenli online ödeme, bütçe hazırlığı ve düzenli raporlama.' }, technical: { title: 'Teknik bakım, arıza ve onarım', description: 'Elektrik, tesisat, asansör, jeneratör ve acil durum süreçlerinin takibi.' }, communication: { title: 'Temizlik, güvenlik ve danışma', description: 'Planlı hijyen, personel koordinasyonu ve giriş-çıkış organizasyonu.' }, legal: { title: 'Hukuki ve idari yönetim', description: 'Aidat takibi, genel kurul, sözleşme ve yönetim planı süreçlerinde uzman destek.' }
  },
  process: { title: 'Birlikte çalışmaya nasıl başlıyoruz?', subtitle: 'İlk görüşmeden düzenli yönetime kadar açık ve ölçülebilir beş adım.', steps: [
    { title: 'Bize ulaşın', description: 'İhtiyaçlarınızı dinleyelim ve kısa bir ön görüşme planlayalım.' }, { title: 'Site analizi', description: 'Mevcut bütçeyi, teknik durumu ve açık işleri birlikte inceleyelim.' }, { title: 'Şeffaf teklif', description: 'Kapsamı ve sorumlulukları net, karşılaştırılabilir bir teklif sunalım.' }, { title: 'Genel kurul', description: 'Planı kat maliklerine anlaşılır verilerle aktaralım.' }, { title: 'Yönetimi devralalım', description: 'Takvimli raporlama ve düzenli saha takibiyle başlayalım.' }
  ] },
  technology: { title: 'Yönetim, herkes için daha görünür', subtitle: 'Dijital araçlarla ödeme, talep ve duyuruları tek bir akışta buluşturuyoruz.', features: [
    { title: 'Mobil erişim', description: 'Site gündemine ve duyurulara her yerden ulaşın.' }, { title: 'Online ödeme', description: 'Aidat ve ortak gider ödemelerini güvenle takip edin.' }, { title: 'Yönetim paneli', description: 'Bütçe, iş emri ve raporları tek ekranda görün.' }, { title: 'Talep takibi', description: 'Bakım taleplerinin durumunu ve sonucunu izleyin.' }
  ] },
  trust: { eyebrow: 'Güven, şeffaflık ve uzmanlık', title: 'Sadece yönetmiyor, daha iyi bir yaşam için çalışıyoruz.', description: 'Mali, hukuki, idari ve teknik süreçleri uzman ekiplerin koordinasyonuyla yürütüyor; kat maliklerinin haklarını gözeten, hesap verebilir bir düzen kuruyoruz.', link: 'Neden profesyonel yönetim?', items: ['Şeffaflık', 'Mevzuata uyum', 'Hızlı koordinasyon', 'Hesap verebilirlik'], faqEyebrow: 'Sıkça sorulan sorular', faqTitle: 'Profesyonel yönetim hakkında merak edilenler.', faqs: [
    { question: 'Apartman veya sitelerde yönetici atanması zorunlu mudur?', answer: '634 sayılı Kat Mülkiyeti Kanunu’nun 34. maddesine göre, anagayrimenkulde sekiz veya daha fazla bağımsız bölüm varsa yönetici atanması zorunludur. Dışarıdan profesyonel yönetici veya yönetim hizmeti de tercih edilebilir.' }, { question: 'Aidat ve ortak giderler hangi esaslara göre paylaştırılır?', answer: 'Kat Mülkiyeti Kanunu’nun 20. maddesi ve yönetim planı esas alınır. Somut dağıtımda geçerli yönetim planı ve kurul kararları ayrıca incelenmelidir.' }, { question: 'Mevcut bir yönetimin devrini alabilir misiniz?', answer: 'Evet. Belge, hesap, karar ve devam eden işleri inceleyerek kontrollü ve kayıtlı bir devir teslim planı hazırlıyoruz.' }, { question: 'İlk görüşme ne zaman yapılır?', answer: 'Teklif formunuz bize ulaştıktan sonra en geç 24 saat içinde ilk değerlendirme için sizinle iletişime geçiyoruz.' }
  ], ctaEyebrow: 'Ücretsiz ön keşif', ctaTitle: 'Binanız için doğru yönetim planını birlikte oluşturalım.', ctaButton: 'Teklif alın' }
};

export default tr;
